apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "httpforward.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "httpforward.name" . }}
data:
  default.conf: >-
            server {
              listen 80;
              listen [::]:80;

              location / {
                  proxy_pass {{ .Values.target }};
              }
            }
    

    
